### ISSUE TITLE
Journal requirements

### ISSUE THREAD

**Issue by paolap** [ACDguide/Governance#12]
I added a list of journal publishers with their data requirements in the appendix section.

Is this useful? If yes I can fill all the other as for AGU, see page:

https://acdguide.github.io/Governance/appendix/journals.html

NB you need to click the dropdown box to see all the relevant info.

I have the information on the CMS wiki, so this has been checked recently. It is just a bit more fiddly to put it in this format and I won't do it unless we're all happy with it.

**Comment by hot007** [comment]
I would say worth including, but maybe include a "last checked" date at the top for each one so people are not surprised if the page is 2 years old and the journal expectations have changed.

**Comment by paolap** [comment]
Yep I guess we could put a disclaimer for content like this that could be going out of date. Ideally if this experiment is useful and we get more contributors then it might be easier to keep it updated. I'll add more on Monday :-)

**Comment by organisergirl** [comment]
Open access policy info can be found here too if this is of use https://v2.sherpa.ac.uk/romeo/

**Comment by paolap** [comment]
This is complete
