### ISSUE TITLE
Define DOI

### ISSUE THREAD

**Issue by hot007** [ACDguide/Governance#20]
The term DOI is not defined anywhere in this book. Given it is used in many places I'm not sure where the best place to put the definition is!

**Comment by hot007** [comment]
Actually that's not true, I do spell out the acronym on the retirement page, but I think we need to actually explain them properly somewhere - what they're for, when to use them etc, maybe on the publication page, otherwise key concepts?

**Comment by paolap** [comment]
That's when we use concepts: file:///Users/paolap/ACDguide/Governance/Governance/_build/html/concepts/pids.html

Feel free to improve the definition, would you want a reference added? So then it can be cross-referenced in other part of the book?

**Comment by paolap** [comment]
Actually I just checked and it has already a label, you can cross-reference doing
{ref}`doi` this will produced a link like the header which is currently Digital Object Identifier.

For example:
"   to do so you use {ref}`doi`   "  would appear as

"  to do so you use [Digital Object Identifier](https://acdguide.github.io/Governance/concepts/pids.html#digital-object-identifier) "

We could change the header if we prefer "DOI" as text

**Comment by hot007** [comment]
ooh that's awesome! I'll just leave this issue to float for now but when we're in the final stages of pulling the book together I'll try to go through and apply this.

**Comment by paolap** [comment]
Closing this and create new issue about linking concepts in book at the end
