### ISSUE TITLE
Add 'advanced' data mgmt page 

### ISSUE THREAD

**Issue by hot007** [ACDguide/Governance#34]
Add a page for advanced users - data custodians and stewards in technical data management at NCI:
- writers group creation
- use of posix permissions
- use of ACLs
- caveats with ACLs - what breaks them and when do they break?
Note, this is NCI specific content - on CSIRO internal resources e.g., access mgmt is governed by windows ACLs - email schelp for advice.

Build on 
- Paola's cheatsheet (link?)
- Damien's doco

First draft to be written by @hot007 or @paolap ; @chloemackallah  to review.

**Comment by hot007** [comment]
Does this go under "[updating](https://acdguide.github.io/Governance/update/update-intro.html)"? Should "updating" be renamed "managing" and include updating existing datasets alongside guidance on managing data access and when to review?

**Comment by chloemackallah** [comment]
Oh that's a good idea. What were you current plans for the updating section?

**Comment by paolap** [comment]
I was thinking of something but in fact it would have been really small, so I think Claire's idea is excellent, it really is a part of managing the data :-)

**Comment by paolap** [comment]
The cheatsheet is here: https://docs.google.com/document/d/1pGgVAoEjErHTn4joiCXbdnZDppEXwq9RcNofedrViz4/edit
It's mostly useful to check the different command options

**Comment by paolap** [comment]
I'm working on this now, will push asap I have a draft

**Comment by paolap** [comment]
I'm closing this as we got the section there even if it needs more work
