### ISSUE TITLE
Review contents and standardise pronouns/voice

### ISSUE THREAD

**Issue by hot007** [ACDguide/Governance#59]
Editorial checks and make sure use of we/you/passive voice is appropriate and reasonably consistent.

**Comment by hot007** [comment]
Create links between pages where needed (particularly 'concepts' and 'tech tips' pages)

**Comment by paolap** [comment]
I've just noticed that I still hadn't tidied up the open-license information I copied from the CMS wiki, so there's a lot of you-ing going on there. I'm trying to make it more impersonal, and I will push this asap

**Comment by paolap** [comment]
I now hopefully fix this in the licenses files, which was good as there was a lot more to fix :-)

**Comment by rlgregory** [comment]
Done a first review of the we/you/passive voice. Expect we will need to raise and do again as book develops further.
