### ISSUE TITLE
deciding on parts (i.e. main division level):

### ISSUE THREAD

**Issue by paolap** [ACDguide/Governance#6]
Now we have parts for the actual guidelines:
create data
publish data
retire data

Technical: DRS, calendars, chunking, what breaks a tool (attributes needed to make some tools work), data formats

Concepts: moving vocabularies, conventions, key concepts in here and then referred to them when their needed in other parts.

Appendix: for lists/tables

**Comment by chloemackallah** [comment]
Adding 'About us' Section

**Comment by paolap** [comment]
This can be closed as we have the main structure sorted out now
