### ISSUE TITLE
fix references in create section

### ISSUE THREAD

**Issue by paolap** [ACDguide/Governance#61]
@chloemackallah some of the references to other chapters in the create section are broken, so I was going to fix them.
I'm not sure here if you're trying to refer to the Concept section or the Concept sand the appendix section:
(Note that we will use terms and concepts described in Appendix/concepts (appendix/concepts.md).
Based on the link I'm assuming is the first option.

**Comment by paolap** [comment]
To be clear most of these were in the create-basic.md files and most of them were because the file was referenced as if from the main directory
(tech/massdata.md) rather than from the create/ directory:
(../tech/massdata.md)

I also pick a bunch of other links across the all book that needed fixing particularly in relation to backup.md which has moved from "tech" to "concepts".

**Comment by chloemackallah** [comment]
I had a bit of confusion because there were similar pages in tech and concepts, so I didn't make much effort to clean them up. Thanks!
