### ISSUE TITLE
Check key concepts all covered

### ISSUE THREAD

**Issue by hot007** [ACDguide/Governance#71]
There are some 'concepts' pages that are not linked from the title page in the 'Concepts' section - update links to ensure they're all linked.

In Appendices, remove 'key concepts' page, or rename to 'Glossary' and remove all the things that appear in Concepts.

**Comment by paolap** [comment]
@hot007 after having a look at this I think it might be better to have acronyms and glossary as one glossary. Then we can reference all of them in the same way. Also some of the terms here are also acronyms so dividing them in two categories is kind of confusing. See FAIR it's an acronym but it's also a concept.

**Comment by hot007** [comment]
Fair point! (boom tish)
